import { v4 as uuidv4 } from 'uuid'

export const routes = {
   home: '/',
   login: '/login',
   about: '/about',
   system: '/sistemas',
}

export const users = ['iarriagada', 'sacuna', 'rdelcanto', 'fmarin', 'caraneda']

export const systems = [
   {
      id: uuidv4(),
      title: 'registro de avance',
      desc: 'Controla tus actividades de trabajo.',
      url: 'http://www.zcloud.cl/registro_avance/index.php',
      icon: 'fas fa-clipboard-list',
      tecno: 'php',
      env: 'pro',
   },
   {
      id: uuidv4(),
      title: 'control de actividades',
      desc: 'Revisa tus actividades, crea tareas, notas y actividades y revisa tu tiempo de trabajo.',
      url: `https://todo.zproduccion.cl/#/`,
      icon: 'fas fa-clipboard-list',
      tecno: 'react',
      env: 'pro',
   },
   {
      id: uuidv4(),
      title: 'plataforma clientes',
      desc: 'Revisa, crea eventos y nuevos ticket para solicitar ayuda.',
      url: `https://tickets.zproduccion.cl/#/`,
      icon: 'fas fa-ticket-alt',
      tecno: 'react',
      env: 'pro',
   },
   {
      id: uuidv4(),
      title: 'health',
      desc: 'Observa informacion importante de forma rapida y directa sobre tu empresa.',
      url: `https://health.zproduccion.cl`,
      icon: 'fas fa-heartbeat',
      tecno: 'react',
      env: 'pro',
   },
   {
      id: uuidv4(),
      title: 'plataforma comercial',
      desc: 'Administrar las potenciales soluciones para tus clientes.',
      url: `http://zcloud.cl/pce/`,
      icon: 'fas fa-heartbeat',
      tecno: 'react',
      env: 'pro',
   },
   {
      id: uuidv4(),
      title: 'recetas',
      desc: 'Observa como se componen tus productos.',
      url: `https://recetas.zproduccion.cl`,
      icon: 'fas fa-heartbeat',
      tecno: 'react',
      env: 'pro',
   },
   {
      id: uuidv4(),
      title: 'factura electronica',
      desc: 'Firma, genera y valida facturas de tu empresa.',
      url: `https://factura.zproduccion.cl`,
      icon: 'fas fa-heartbeat',
      tecno: 'react',
      env: 'pro',
   },
   {
      id: uuidv4(),
      title: 'picoltue',
      desc: 'Obserba en avence de cosechas de tu empresa.',
      url: `https://picoltue.zproduccion.cl/#/`,
      icon: 'fas fa-chart-bar',
      tecno: 'react',
      env: 'pro',
   },
   {
      id: uuidv4(),
      title: 'Curimapu export',
      desc: 'ERP para empresa curimapu.',
      url: `http://www.zcloud.cl/curimapu/index.php`,
      icon: 'fas fa-heartbeat',
      tecno: 'php',
      env: 'pro',
   },
   {
      id: uuidv4(),
      title: 'reservas',
      desc: 'Sistema de reserva para profesionales.',
      url: `http://www.zcloud.cl/reservas`,
      icon: 'fas fa-heartbeat',
      tecno: 'php',
      env: 'pro',
   },
   {
      id: uuidv4(),
      title: 'BNC activa',
      desc: 'Sistema de recetas para BNC.',
      url: `http://pruebas-erp.cl/bcn02/receta_ver.php?n=1`,
      icon: 'fas fa-heartbeat',
      tecno: 'php',
      env: 'pro',
   },
   {
      id: uuidv4(),
      title: 'Detenciones',
      desc: 'Obserba las deteneciones de tus trabajadores en tiempo real.',
      url: `http://www.zcloud.cl/puntos`,
      icon: 'fas fa-heartbeat',
      tecno: 'php',
      env: 'pro',
   },
   {
      id: uuidv4(),
      title: 'Trabaje',
      desc: 'Sistema para el reclutamiento de personal.',
      url: `http://www.zcloud.cl/curimapu_tcn/`,
      icon: 'fas fa-heartbeat',
      tecno: 'php',
      env: 'pro',
   },
   {
      id: uuidv4(),
      title: 'ERP huertos collipulli',
      desc: 'ERP para CRS.',
      url: `http://zcloud.cl/erp-hc`,
      icon: 'fas fa-heartbeat',
      tecno: 'php',
      env: 'pro',
   },
   // desarrollo
   {
      id: uuidv4(),
      title: 'control de actividades',
      desc: 'Revisa tus actividades, crea tareas, notas y actividades y revisa tu tiempo de trabajo.',
      url: `http://todo.zpruebas.cl/#/`,
      icon: 'fas fa-clipboard-list',
      tecno: 'react',
      env: 'dev',
   },
   {
      id: uuidv4(),
      title: 'plataforma clientes',
      desc: 'Revisa, crea eventos y nuevos ticket para solicitar ayuda.',
      url: `http://tickets.zpruebas.cl/#/`,
      icon: 'fas fa-ticket-alt',
      tecno: 'react',
      env: 'dev',
   },
   // {
   //    id: uuidv4(),
   //    title: 'health',
   //    desc: 'Observa informacion importante de forma rapida y directa sobre tu empresa.',
   //    url: `http://health.zpruebas.cl`,
   //    icon: 'fas fa-heartbeat',
   //    tecno: 'react',
   //    env: 'dev',
   // },
   {
      id: uuidv4(),
      title: 'recetas',
      desc: 'Observa como se componen tus productos.',
      url: `http://recetas.zpruebas.cl`,
      icon: 'fas fa-heartbeat',
      tecno: 'react',
      env: 'dev',
   },
   {
      id: uuidv4(),
      title: 'factura electronica',
      desc: 'Firma, genera y valida facturas de tu empresa.',
      url: `http://factura.zpruebas.cl`,
      icon: 'fas fa-heartbeat',
      tecno: 'react',
      env: 'dev',
   },
   {
      id: uuidv4(),
      title: 'picoltue',
      desc: 'Obserba en avence de cosechas de tu empresa.',
      url: `http://picoltue.zpruebas.cl/#/`,
      icon: 'fas fa-chart-bar',
      tecno: 'react',
      env: 'dev',
   },
]
